api_version = "2024-07"

[[extensions]]
name = "example-checkout-address--js"
handle = "example-checkout-address--js"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/suggest.js"
target = "purchase.address-autocomplete.suggest"

[extensions.capabilities]
api_access = true
network_access = true
